version: "3.7"
services:
  app:
    build:
      args:
        user: dutra
        uid: 1000
      context: ./docker/php
      dockerfile: Dockerfile
    image: lumen-app
    container_name: lumen-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - lumen-app

  db:
    image: mysql:5.7
    container_name: lumen-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - lumen-app

  nginx:
    image: nginx:alpine
    container_name: lumen-webserver
    restart: unless-stopped
    ports:
      - 80:80
    volumes:
      - ./:/var/www
      - ./docker/nginx:/etc/nginx/conf.d/
    networks:
      - lumen-app

networks:
  lumen-app:
    driver: bridge
